"""initial schema

Revision ID: 0b71e561a5c9
Revises: 
Create Date: 2026-04-01 15:25:20.301379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b71e561a5c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_type')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_column('prepractice_duration')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('prepractice_duration', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    op.create_table('training_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('label_short', sa.VARCHAR(length=50), nullable=False),
    sa.Column('label_training_singular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('label_training_plural', sa.VARCHAR(length=100), nullable=False),
    sa.Column('label_term_singular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('label_term_plural', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
